config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users

  resources :wikis do 
    resources :collaborations
  end

  resources :charges, only: [:new, :create]
  
  get 'welcome/index'
  get 'welcome/about'

  root to: 'welcome#index'

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base

  belongs_to :user
  belongs_to :wiki

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base

  belongs_to :user
  belongs_to :wiki

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :collaborations
  has_many :wikis, through: :collaborations


  before_create :make_standard

  def standard?
    role == 'standard'
  end

  def premium?
    role == 'premium'
  end

  def admin?
    role == 'admin'
  end

  def downgrade_account
    self.update_attribute(:role, 'standard')
  end
  
  

  private

  def make_standard
    self.role = 'standard'
  end
  
end

app/models/wiki.rb
include ApplicationHelper

class Wiki < ActiveRecord::Base


  has_many :collaborations
  has_many :users, through: :collaborations


  #after_initialize :make_public
  ## Method causes problems when making wikis private

  default_scope { order('title ASC') }


  def private?
   self.private == true
  end

  def public?
   self.private == false
  end

  def markdown_title
    markdown_to_html (self.title)
  end

  def markdown_body
    markdown_to_html (self.body)
  end

  def available_users
      available = []

      User.order(name: :asc).each do |user|
        available << user unless self.users.include?(user)
      end

      return available

  end

  private

  def make_public
    self.private = false
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


   rescue_from Pundit::NotAuthorizedError do |exception|
     redirect_to root_url, alert: exception.message
   end
   
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  after_action :make_premium, only: :create

  def new
     @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Blocipedia Premium Account - #{current_user.name}",
     amount: 15_00
   }

  end

  def create
  # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
 
   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: 15_00,
     description: "Blocipedia Premium Account - #{current_user.email}",
     currency: 'usd'
   )
 
   flash[:success] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
   redirect_to user_path(current_user) # or wherever
 
 # Stripe will send back CardErrors, with friendly messages
 # when something goes wrong.
 # This `rescue block` catches and displays those errors.
 rescue Stripe::CardError => e
   flash[:error] = e.message
   redirect_to new_charge_path
 end

private

def make_premium
    current_user.update_attribute(:role, 'premium')
    current_user.save!
end

end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController

  before_action :set_wiki

  def new
    @collaboration = @wiki.collaborations.new
    authorize @collaboration
  end

  def show
    @collaboration = Collaboration.find(params[:id])
  end

  def create
    @collaboration = @wiki.collaborations.new( collaboration_params )

     if @collaboration.save
       flash[:notice] = "Collaboration was saved."
       redirect_to @wiki
     else
       flash[:error] = "Error. Could not save the collaboration."
       redirect_to @wiki
     end
  end

  def destroy
    @collaboration = Collaboration.find(params[:id])

    if @collaboration.destroy
       flash[:notice] = " #{@collaboration.user.name} was successfully removed."
       redirect_to @wiki
     else
       flash[:error] = "Error. Could not remove the collaboration."
       redirect_to @wiki
     end
  end

  private

  def set_wiki
    @wiki = Wiki.find(params[:wiki_id]) 
  end 

  def collaboration_params
    params.require(:collaboration).permit(:wiki_id, :user_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @wikis = @user.wikis.paginate(page: params[:page], per_page: 10)
    authorize @user
    #@wikis = policy_scope(Wiki)
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User account downgraded"
      publicize_wikis
      redirect_to welcome_index_path
    else
      flash[:error] = "Invalid user info"
      redirect_to welcome_index_path
    end
  end
 
   private
 
   def user_params
     params.require(:user).permit(:name, :email, :role)
   end

   def publicize_wikis
     current_user.wikis.each do |wiki|
       wiki.update_attribute(:collaborations, [wiki.collaborations.first]) # goes back to original user
       wiki.update_attribute(:private, false)
     end
   end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end

  def about

  end

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController


  def index
    @public_wikis = Wiki.where(private: false).paginate(page: params[:page], per_page: 10)
    authorize @public_wikis
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)

      if current_user.standard?
        @wiki.update_attribute(:private, false)
      end

    @wiki.users.push(current_user) # Wiki needs to have an initial user/collaboration
    authorize @wiki

     if @wiki.save
       flash[:notice] = "Wiki was saved."
       redirect_to @wiki.users.first
     else
       flash[:error] = "Error. Couuld not save the wiki."
     end

  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = @wiki.available_users
    authorize @wiki
  end

  def update
     @wiki = Wiki.find(params[:id])
     
     if @wiki.update_attributes(wiki_params)
       flash[:notice] = "Updated the wiki."
       redirect_to @wiki
     else
       flash[:error] = "Could not update wiki. Please try again."
       render :edit
     end
   end

   def destroy
     @wiki = Wiki.find(params[:id])
 
     if @wiki.destroy
       flash[:notice] = "\"#{@wiki.title}\" has been deleted."
       redirect_to @wiki.users.first
     else
       flash[:error] = "Could not delete the wiki."
       render :show
     end
   end


  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :collaborations)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end


end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborations_helper.rb
module CollaborationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
 <%= form_tag charges_path do %>

   <div class = 'teal box centered-text shift-down move-to-center'> Upgrade account to premium! <br> <br>
     <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" >
     </script>
   </div>


 <% end %>

app/views/collaborations/new.html.erb
<h1>Add User</h1>

<%= form_for [@wiki, Collaboration.new()] do |f| %>

<div class="form-group">
  <%= f.collection_select :user_id, @wiki.available_users, :id, :name, :prompt => true %>
</div>

<div class="form-group">
  <%= f.submit "Save", class: 'green-btn centered-text btn-success' %>
</div>

<% end %>

app/views/collaborations/remove.html.erb
<h1>Remove User</h1>

<%= form_for [@wiki, Collaboration.new()] do |f| %>

<div class="form-group">
  <%= f.collection_select :user_id, @wiki.available_users, :id, :name, :prompt => true %>
</div>

<div class="form-group">
  <%= f.submit "Save", method: 'btn btn-success' %>
</div>

<% end %>

app/views/collaborations/show.html.erb
<br> <br> <%= @collaboration.user.name%> is collaborating on the wiki <%= @wiki.title %> 

app/views/collaborators/new.html.erb
<h1>Add User</h1>

<%= form_for [@wiki, Collaborator.new()] do |f| %>

<div class="form-group">
  <%= f.collection_select :user_id, @wiki.available_users, :id, :name, :prompt => true %>
</div>

<div class="form-group">
  <%= f.submit "Save", class: 'green-btn centered-text btn-success' %>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

       <div class="pull-left shift-right">
         <%= link_to "Home", welcome_index_path %>
       </div>

       <div class="pull-left shift-right">
         <%= link_to "Public Wikis", wikis_path %>
       </div>

       <div class="pull-left shift-right">
         <% if current_user %>
         <%= link_to "My Wikis", current_user %>
         <% end %>
       </div>

        <div class="pull-right shift-left user-info">
         <% if current_user %>
             Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %>
           <% end %>
         </div>
         
    <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>


<% @users.each do |user| %>
<p>

  <div class = 'row'>

    <div class="col-md-2 col-md-offset-3"> 
      <%= link_to user.name, user %>
    </div>

   <!--  <div class="col-md-2"> 
      <%= user.email %>
    </div> -->

    <div class="col-md-2"> 
      <%= user.role %> user
    </div>

  </div>

</p>

<% end %>

<%= will_paginate @users %>

app/views/users/show.html.erb
<% if @user == current_user %>
<h1>My Wikis</h1>
<% else %>
<h1> <%= @user.name %></h1>
<% end %>

<br>

<% @wikis.each do |wiki| %> 

<% if wiki.users.include?(current_user) || wiki.public? %>

<p>

<div class = 'row'>
  

  <div class="col-md-2 col-md-offset-2 no-overflow"> 
    <%= link_to wiki.markdown_title, wiki %> 
  </div> 

  <div class="col-md-2 no-overflow">
    <% if policy(wiki).edit? %>
    <%= link_to "Edit", edit_wiki_path(wiki) %>
    <% end %>
  </div>

  <div class="col-md-2 no-overflow">
    <% if wiki.private? && current_user == wiki.collaborations.first.user%>
    <%= link_to "Add user", new_wiki_collaboration_path(wiki) %>
    <% end %>
  </div>


  <div class="col-md-2 no-overflow">
    <% if policy(wiki).destroy? %>
    <%= link_to "Delete", wiki, method: :delete %>
    <% end %>
  </div>

</div>

</p>

<% end %>

<% end %>


<%= will_paginate @wikis %>


<div class="col-md-2 col-md-offset-5">
  <% if @user == current_user %>
  <%= button_to "New Wiki", new_wiki_path, :class => "green-btn centered-text move-to-center", 
  :method => :get %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<br>
<h1>Welcome to Blocipedia: Social Wikis</h1>

<div class = 'teal box centered-text shift-down move-to-center'> Create and share your Wikis!
  <% if !current_user %>
    <%= button_to "Sign Up", new_user_registration_path, :class => "green-btn centered-text", 
    :method => :get %>
  <% end %>
</div>


<div class = 'row'>

  <div class="col-md-4 col-md-offset-2 shift-down">Create unlimited number<br>
  of free wikis with free plan<br> 
      <% if current_user && current_user.premium? %>

        <%= form_for current_user do |f| %>
          <%= f.submit "Free", data: { confirm: "Downgrade account to free status?" }, 
          class: "green-btn centered-text" %>
          <%= f.hidden_field :role, :value => 'standard'%>
        <% end %>

      <% end %>
  </div> 

  <div class="col-md-4 col-md-offset-2 shift-down">Create private wikis<br> with
    premium plan<br>
      <% if current_user && current_user.standard? %>
        <%= button_to "Premium", new_charge_path, :class => "green-btn centered-text", 
        :method => :get %>
      <% end %>
  </div>

</div>

app/views/wikis/edit.html.erb
 <br>
 <h1>Edit Wiki</h1>
 
 <div class = "tall teal container">


 <div class="row">
   <div class="col-md-4 col-md-offset-2">
     <%= form_for @wiki do |f| %>
       <div class="long form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="long form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki content" %>
       </div>
       <div class="form-group">
         <% if current_user.premium? && @wiki.collaborations.first.user == current_user%>
           <%= f.check_box :private, {checked: @wiki.private?} %>
           <%= f.label "Private" %>
         <% end %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

</div>

app/views/wikis/index.html.erb
<br>
<h1>Public Wikis</h1>

<% @public_wikis.each do |wiki| %>

<p>
 <div class = 'row'>

  <div class="col-md-2 col-md-offset-3 no-overflow"> 
    <%= link_to wiki.markdown_title, wiki %> 
  </div> 

  <div class="col-md-2 col-md-offset-2 no-overflow">
    <% if policy(wiki).edit? %>
    <%= link_to "Edit", edit_wiki_path(wiki) %>
    <% end %>
  </div>

  </div>
</p>

 <% end %>

  <br>
  <%= will_paginate @public_wikis %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
 

 <div class = "tall teal container">

 <div class="row">
   <div class="col-md-4 col-md-offset-2">
     <%= form_for @wiki do |f| %>
       <div class="long form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="long form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki content" %>
       </div>
       <div class="form-group">
         <% if current_user.premium? %>
           <%= f.check_box :private, {checked: @wiki.private?} %>
           <%= f.label "Private" %>
         <% end %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

 </div>

app/views/wikis/show.html.erb
<div class = "tall teal scrollable container">

<h1> <%= @wiki.markdown_title %></h1>
<p> <%= @wiki.markdown_body %></p>

<p> Created by: <%= @wiki.collaborations.first.user.name %> 

<% if @wiki.private?%>

<p> Shared with:
 <% @wiki.collaborations.each do |c| %>

<div class = 'row'>

<% if c.user != @wiki.collaborations.first.user  %>

  <div class="col-md-4 col-md-offset-2"> 
     <%= c.user.name %>
  </div> 

  <div class="col-md-4">
    <% if current_user == @wiki.collaborations.first.user%>
    <%= link_to "Remove", wiki_collaboration_path(@wiki, c), method: :delete %>
    <% end %>
  </div>

<% end %> 

</div>


 <% end %>
</p>

<% end %>

</div>